config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  resources :users
  resources :exchanges
  resources :login, only: [:new, :create]
  get "/users/:id/portfolio", to: "users#portfolio", as: "portfolio"
  get "/", to:"login#new"
  get "/logout", to: "login#logout", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  has_many :exchanges
  has_many :users, through: :exchanges
  require "uri"
  require "net/http"


#   def update_price
#     url = "https://blockchain.info/ticker"
#     response = RestClient.get(url)
#     response_hash = JSON.parse(response)
#     usd = response_hash["USD"]
#     self.update(buy_price: usd["buy"], sell_price: usd["sell"], spot_price: usd["15m"])
#   end
#
#   def dollar_to_unit(amount)
#     url = "https://blockchain.info/tobtc?currency=USD&value=#{amount}"
#     response = RestClient.get(url)
#     units = JSON.parse(response) #number of units bought with this amount
#   end
#
# end

  def update_price
    url = "api.coincap.io/v2/assets/#{self.api_id}"
    response = RestClient.get(url)
    response_hash = JSON.parse(response)
    data_price = response_hash["data"]["priceUsd"]
    self.update(spot_price: data_price)
  end

end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :crypto
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exchanges, dependent: :destroy
  has_many :cryptos, through: :exchanges

  validates :username, presence: true
  validates :username, uniqueness: true

  validates :password, length: { minimum: 8 }, allow_blank: false

  has_secure_password

  def can_buy?(amount)
    self.balance < amount ? false : true
  end

  def can_sell?(units)
    crypto_owned_total >= units ? true : false
  end

  def investment_total
    buys_total - sells_total
  end

  def buys
    self.exchanges.select { |ex| ex.buy }
  end

  def sells
    self.exchanges.select { |ex| !ex.buy }
  end

  def buys_total
    (buys.map {|buy| buy.market_price * buy.units}).sum
  end

  def sells_total
    (sells.map {|sell| sell.market_price * sell.units}).sum
  end

  def crypto_buys
    (buys.map {|buy| buy.units}).sum
  end

  def crypto_sells
    (sells.map {|sell| sell.units}).sum
  end

  def crypto_owned_total
    crypto_buys - crypto_sells
  end

  def performance
    self.investment_value + self.balance - 100000
  end

  def crypto_total
    buy_hash = self.buys.inject(Hash.new(0)) do |hash, exchange|
      hash[exchange.crypto.name] += exchange.units
      hash
    end
    complete_hash = self.sells.inject(buy_hash) do |hash, exchange|
      hash[exchange.crypto.name] -= exchange.units
      hash
    end
    complete_hash
  end

  def investment_value
    cryptos_owned = self.crypto_total
    cryptos_owned.inject(0) do |total, (crypto, value)|
        crypto_object = Crypto.find_by(name: crypto)
        if value > 0
          crypto_object.update_price
        end
        total += crypto_object.spot_price * value
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :logged_in

    def logged_in
        @notification = flash[:notification]
        @errors = flash[:errors]
        if session[:user_id]
            @logged_in_user = User.find(session[:user_id])
            @can_exchange = true
        end
    end


end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:update, :edit, :show]

  def index
    @cryptos = Crypto.all
    @cryptos = @cryptos.sort_by {|currency| currency.name}
  end

  def show
    @crypto.update_price
    @exchange = Exchange.new
  end

  private

  def set_crypto
      @crypto = Crypto.find(params[:id])
  end

  def crypto_params
      params.require(:crypto).permit(
          :name,
          :buy_price,
          :spot_price,
          :sell_price
      )
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController


    def create
      @exchange = Exchange.new(exchange_params)
      session[:exchange_amount] = exchange_amount
      if @exchange.buy
        buy
      else
        sell
      end
    end

    private

    def exchange_amount
      params[:exchange][:units].to_f * params[:exchange][:market_price].to_f
    end

    def buy
      if @exchange.user.can_buy?(exchange_amount)
        @exchange.save(validate: false)
        session[:buy] = true
        redirect_to portfolio_path(@exchange.user)
      else
        flash[:errors] = ["You don't have those funds"]
        redirect_to @exchange.crypto
      end

    end

    def sell
      if @exchange.user.can_sell?(params[:exchange][:units].to_f)
        @exchange.save(validate: false)
        session[:buy] = false
        redirect_to portfolio_path(@exchange.user)
      else
        flash[:errors] = ["You don't have that many units"]
        redirect_to @exchange.crypto
      end

    end


    def exchange_params
        params.require(:exchange).permit(
            :user_id,
            :crypto_id,
            :units,
            :buy,
            :market_price
        )
    end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

    def logout
        session.clear
        flash[:notification] = ["Logged out"]
        redirect_to "/"
    end

    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to "/users/#{@user.id}/portfolio"
        else
            flash[:errors] = ["Incorrect username or password. Denied."]
            redirect_to '/'
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:destroy, :update, :edit, :show, :portfolio]


    def show
        if !@logged_in_user == @user || !@logged_in_user
            flash[:errors] = ["You don't have permission to view that page"]
            redirect_to new_login_path
        end
    end

    def new
        @user = User.new(flash[:attributes])
    end

    def create
        @user = User.new(user_params)
        @user.save ? saved(@user) : error_load(@user)
    end

    def update
        if @user.update(user_params)
          redirect_to @user
        else
          redirect_to edit_user_path(@user)
        end
    end

    def portfolio
      if session[:exchange_amount]
        if session[:buy] == true
            @user.balance -= session[:exchange_amount]
        elsif session[:buy] == false
            @user.balance += session[:exchange_amount]
        end
        @user.save(validate: false)
        session[:exchange_amount] = nil
        session[:buy] = nil
      end
    end

    def destroy
        @user.destroy
        flash[:notification] = ["Account Deleted"]
        session[:user_id] = nil
        redirect_to "/"
    end

    private

    def saved(user)
        session[:user_id] = @user.id
        redirect_to portfolio_path(@user)
    end

    def error_load(user)
        flash[:errors] = user.errors.full_messages
        flash[:attributes] = user.attributes
        redirect_to new_user_path
    end

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(
            :username,
            :email,
            :password,
            :bio,
            :photo_url,
            :balance
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cryptos/_exchange_form.html.erb
<%= form_for @exchange do |f| %>
  <%= f.hidden_field :user_id, value: @logged_in_user.id %>
  <%= f.hidden_field :crypto_id, value: @crypto.id %>
  <%= f.hidden_field :market_price, value: @crypto.spot_price.round(6) %>

  <%= f.label :buy %>
  <%= f.select :buy, [['Buy', true], ['Sell', false]] %>

  <%= f.label :units %>
  <%= f.number_field :units, step: :any %>

  <%= f.submit %>

<% end %>

app/views/cryptos/index.html.erb
<h1>Cryptos:</h1>

<ul>
<% @cryptos.each do |crypto| %>
  <li><%= link_to crypto.name, crypto %></li>
<% end %>
</ul>

app/views/cryptos/show.html.erb
<h1><%= @crypto.name %> (<%= @crypto.symbol %>): $<%= @crypto.spot_price.round(6) %> USD</h1>
<h6> Last Updated: <%=  @crypto.updated_at %> </h6>

<ul>
  <li>Buy Price: $<%= @crypto.spot_price.round(6) %> USD</li>
  <li>Sell Price: $<%= @crypto.spot_price.round(6) %> USD</li>
</ul>

<% if @logged_in_user %>
  <%= render 'exchange_form' %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
</head>
  <body>
    <div class="wrapper-1">
      <div class="nav">
        <% if @logged_in_user %>
          <li class="right-nav">
            <%=  link_to @logged_in_user.username, @logged_in_user %>
          </li>
          <li class="right-nav">
            <%= link_to "LOGOUT", logout_path %>
          </li>
          <li><%= link_to image_tag("/assets/bitcoin.png", :class => "bitcoin" ), cryptos_path %></li>
          <li><%= link_to "CRYPTOS", cryptos_path  %></li>
          <li><%= link_to "PORTFOLIO", portfolio_path(@logged_in_user) %></li>
          <li><%= link_to "EDIT PROFILE", edit_user_path(@logged_in_user) %></li>
        <% end %>
      </div>
  <% if @notification %>
    <h1> <% @notification.each do |note| %> </h1>
      <%=  note %>
    <% end %>
  <% end %>

  <% if @errors && @errors.any? %>
    <% @errors.each do |error| %>
      <%=  error %>
    <% end %>
  <% end %>


  <div class="content">
      <%= yield %>
      <br>
  </div>
  <footer>
    <div>Login graphic made by <a href="https://dribbble.com/DizSergei" title="Sergei Tikhonov">Sergei Tikhonov</a> from <a href="https://isometric.online/"         title="Flaticon">www.isometric.online</a></div>
    <div>Bitcoin icon made by <a href="https://www.flaticon.com/authors/becris" title="Becris">Becris</a> from <a href="https://www.flaticon.com/"         title="Flaticon">www.flaticon.com</a></div>
  </footer>
  </div>

  </body>
</html>

app/views/login/new.html.erb
<html>
<head>
    <title>Crypto Hero</title>
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/login.scss">
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Sign In </h2>
            <h2 class="inactive underlineHover">
              <%= link_to "Sign Up", new_user_path %>
            </h2>

            <!-- Icon -->
            <div class="fadeIn first">
                <img src="/assets/cryptocurrency.png" id="icon" alt="Cryptocurrency Icon" />
            </div>

            <!-- Login Form -->
            <form action="/login" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="text" id="login" class="fadeIn second" name="username" placeholder="username">
                <input type="password" id="password" class="fadeIn third" name="password" placeholder="password">
                <input type="submit" class="fadeIn fourth" value="Log In">
            </form>

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="#">Forgot Password?</a>
            </div>

        </div>
    </div>
</body>
</html>

app/views/users/_form.html.erb
<% if flash[:errors] %>
   <% flash[:errors].each do |error| %>
       <%= error %>
   <% end %>
<% end %>

<%= form_for(@user) do |f| %>
   <%= f.hidden_field :balance, value: 100000.00%>
   <%= f.label :username, :html => {:class => "fadeIn second", :id => "login"} %>
   <%= f.text_field :username, :html => {:class => "fadeIn second", :id => "login"} %>
   <br>
   <%= f.label :password, :html => {:class => "fadeIn third", :id => "password"} %>
   <%= f.password_field :password, :html => {:class => "fadeIn third", :id => "password"} %>
   <br>
   <%= f.submit :html => {:class => "fadeIn fourth"} %>
<% end %>

app/views/users/edit.html.erb
<title>Crypto Hero | Edit Account</title>
<h1> Edit Account </h1>

<%= form_for(@user) do |f| %>
  <%= f.hidden_field :password, value: @user.password_digest %>
   <%= f.label :username, "Change your username:" %>
   <br>
   <%= f.text_field :username %>
   <br>
   <br>
   <%= f.label :photo_url, "Add a url for a profile picture:" %>
   <br>
   <%= f.text_field :photo_url %>
   <br>
   <br>
   <%= f.label :bio, "Add a short bio:" %>
   <br>
   <%= f.text_area :bio %>
   <br>
   <br>
   <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<html>
<head>
    <title>Crypto Hero</title>
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/login.scss">
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active"> Sign Up </h2>
            <h2 class="inactive underlineHover">
              <%= link_to "Sign In", '/' %>
            </h2>

            <!-- Icon -->
            <div class="fadeIn first">
                <img src="/assets/cryptocurrency.png" id="icon" alt="Cryptocurrency Icon" />
            </div>

            <!-- Login Form -->
            <%= form_for(@user) do |f| %>
               <%= f.hidden_field :balance, value: 100000.00%>
               <%= f.label :username, :html => {:class => "fadeIn second", :id => "login"} %>
               <%= f.text_field :username, :html => {:class => "fadeIn second", :id => "login"} %>
               <br>
               <%= f.label :password, :html => {:class => "fadeIn third", :id => "password"} %>
               <%= f.password_field :password, :html => {:class => "fadeIn third", :id => "password"} %>
               <br>
               <%= f.submit :html => {:class => "fadeIn fourth"} %>
            <% end %>

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="#">Forgot Password?</a>
            </div>

        </div>
    </div>
</body>
</html>

app/views/users/portfolio.html.erb
<h1> Portfolio | <%= @user.performance %></h1>

<h3>Account Balance: $<%= @user.balance %></h3>
<h3>Total Live Investments: $<%= @user.investment_value.round(2) %></h3>
<h3>Total Crypto Owned:
    <ul>
        <% @user.crypto_total.each do |k, v| %>
            <% if v != 0 %>
                <li><%=  link_to "#{k} - #{v}", Crypto.find_by(name: k)%></li>
            <% end %>
        <% end %>
    </ul>
</h3>

<h2>Buys</h2>
<div class='main-content'>
  <% if !@user.buys.empty? %>
    <ul>
    <% @user.buys.each do |exchange| %>
        <li> <%= link_to "#{exchange.created_at.to_date} - #{exchange.units} #{exchange.crypto.name} @ #{exchange.market_price}", exchange.crypto %> </li>
    <% end %>

  <% else %>
      <li>No Sells history</li>
    </ul>
  <% end %>
</div>

<h2>Sells</h2>
<div class='main-content'>
  <% if !@user.sells.empty? %>
    <ul>
    <% @user.sells.each do |exchange| %>
        <li> <%= link_to "#{exchange.created_at.to_date} - #{exchange.units} #{exchange.crypto.name} @ #{exchange.market_price}", exchange.crypto %> </li>
    <% end %>

    <% else %>
      <li>No buys history</li>
    </ul>
    <% end %>
</div>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s | Profile </h1>


<p><img src=<%= @user.photo_url %> alt='User's profile picture' height=100px></p>

<ul>
  <li>Email: <%= @user.email %></li>
  <li>Bio:<%= @user.bio %></li>
</ul>

<%= button_to "Delete Account", @user, method: :delete %>